pr: none
trigger: none

parameters:
- name: DeployConfigMap
  displayName: "Deploy Config Map"
  type: boolean
  default: false

resources:
  repositories:
  - repository: BHF.Microservices
    type: github
    endpoint: github.com_wcheung-bhf
    name: BHFDigital/BHF.Microservices
    ref: main

variables:
- name: azureSubscription
  value: 'BHF Shared_NonProd (e014a007-5eec-4a79-9925-752b25ea2aa6)'
- name: containerRegistry
  value: 'bhfmicroservices'
- name: containerRegistryConnection
  value: 'BHF-ACR Connection'
- name: repository
  value: 'BHF.MS.Template' # Change me - repository name
- name: dockerPath
  value: 'code/BHF.MS.MyMicroservice' # Change me - relative path to the folder containing Dockerfile

stages:
  - stage: 'Build_and_Publish_Microservice'
    displayName: 'Build and Publish Microservice'
    jobs:
    - job: 'Build_Microservice'
      displayName: 'Build Microservice'
      steps:
        - template: /devops/templates/build/configure-checkout.yml@BHF.Microservices
          parameters:
            forceShallowFetch: true
        - template: /devops/templates/build/build-microservice.yml@BHF.Microservices
          parameters:
            containerRegistryConnection: '$(containerRegistryConnection)'
            repository:                  '$(repository)'
            dockerPath:                  '$(dockerPath)'
            publish:                     'Y'
            buildContext:                $(Build.Repository.LocalPath)/$(repository)
            
  - stage: Deploy_To_Development
    displayName: 'Deploy to Development'
    condition: succeeded()
    jobs:
      - deployment: 'Deploy_to_Kubernetes'
        displayName: 'Deploy to Kubernetes'
        environment: 'MS-development'
        variables:
          - name:  ContainerReg
            value: $(containerRegistry)
          - name:  BuildRef
            value: '$(build.buildnumber)'
          - name:  KeyVaultUri
            value: 'https://<keyvault_uri>.vault.azure.net/' # Change me - Integration microservice KV instance
          - name:  ManagedIdentityClientId
            value: '6369b0bb-7e77-430b-b32d-d598915e252a'
        strategy:
          runOnce:
            deploy:
              steps:
              - template: /devops/templates/build/configure-checkout.yml@BHF.Microservices
                parameters:
                  forceShallowFetch: true
              - template: /devops/templates/deploy/deploy-kubernetes.yml@BHF.Microservices
                parameters:
                  azureSubscription:  $(azureSubscription)
                  azureResourceGroup: 'uks-microservices-rsg'
                  kubernetesCluster:  'uksbhfmicroservices'
                  DeployConfigMap:    '${{parameters.DeployConfigMap}}'
